/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Member;

import quanlythuvien.*;
import Controller.DAO;
import DATA.QuanLyBao;
import java.awt.Color;
import java.util.ArrayList;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.lang.Exception;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.PreparedStatement;

/**
 *
 * @author loqco
 */
public class BAO_FORM1 extends javax.swing.JFrame {

    /**
     * Creates new form BAO_FORM
     */
    public BAO_FORM1() {
        initComponents();
        Date date = new Date();
        txtNgayPH.setDate(date);
        Show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaBao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTenBao = new javax.swing.JTextField();
        txtMaTaiLieu = new javax.swing.JTextField();
        txtTenTaiLieu = new javax.swing.JTextField();
        txtSoBan = new javax.swing.JTextField();
        txtNXB = new javax.swing.JTextField();
        txtNgayPH = new com.toedter.calendar.JDateChooser();
        A = new javax.swing.JLabel();
        B = new javax.swing.JLabel();
        F = new javax.swing.JLabel();
        E = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBao = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtTenBao1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        btnReload1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("QUẢN LÝ BÁO");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Newspapers-1-icon.png"))); // NOI18N
        jLabel1.setText("THÔNG TIN BÁO");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin báo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Tên Báo");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Mã báo");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Ngày phát hành");

        txtMaBao.setEnabled(false);
        txtMaBao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaBaoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Mã tài liệu");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Tên tài liệu");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("NXB");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Số bản phát hành");

        txtTenBao.setEnabled(false);
        txtTenBao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenBaoActionPerformed(evt);
            }
        });

        txtMaTaiLieu.setText("T003");
        txtMaTaiLieu.setEnabled(false);
        txtMaTaiLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaTaiLieuActionPerformed(evt);
            }
        });

        txtTenTaiLieu.setText("Báo");
        txtTenTaiLieu.setEnabled(false);
        txtTenTaiLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenTaiLieuActionPerformed(evt);
            }
        });

        txtSoBan.setEnabled(false);
        txtSoBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoBanActionPerformed(evt);
            }
        });

        txtNXB.setEnabled(false);
        txtNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNXBActionPerformed(evt);
            }
        });

        txtNgayPH.setDateFormatString("dd-MM-yyyy");
        txtNgayPH.setEnabled(false);
        txtNgayPH.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        A.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        B.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        F.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        E.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTenBao, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B))
                    .addComponent(txtNgayPH, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMaBao, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(A)))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(71, 71, 71))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoBan, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(120, 120, 120)
                        .addComponent(txtNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(F)
                    .addComponent(E))
                .addGap(11, 11, 11))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaBao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenBao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNgayPH, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMaTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTenTaiLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSoBan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E))
                .addGap(19, 19, 19))
        );

        tbBao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tài liệu", "Mã báo", "Tên báo", "Ngày phát hành", "Tên NXB", "Tên tài liệu", "Số bản phát hành"
            }
        ));
        tbBao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbBao);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        txtTenBao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenBao1ActionPerformed(evt);
            }
        });
        txtTenBao1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTenBao1KeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Search-icon (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTenBao1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTenBao1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Refresh.png"))); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnReload1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnReload1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Exit.png"))); // NOI18N
        btnReload1.setText("Cancel");
        btnReload1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReload1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(421, 421, 421)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReload1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReload1)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Connection con = null;
    Statement st = null;
    ResultSet rs = null;

    public ArrayList<QuanLyBao> BaoList() {
        ArrayList<QuanLyBao> BaoList = new ArrayList<QuanLyBao>();
        con = DAO.getConnection();
        String show = "select TaiLieu.MaTaiLieu, MaBao, TenBao, NgayPhatHanh, TenNXB,TenTaiLieu, SoBan from Bao inner join TaiLieu on Bao.MaTaiLieu = TaiLieu.MaTaiLieu";
        try {
            st = con.createStatement();
            rs = st.executeQuery(show);
            QuanLyBao quanlybao;
            while (rs.next()) {
                quanlybao = new QuanLyBao(rs.getString("MaTaiLieu"), rs.getString("MaBao"), rs.getString("TenBao"), rs.getString("NgayPhatHanh"), rs.getString("TenNXB"), rs.getInt("SoBan"), rs.getString("TenTaiLieu"));
                BaoList.add(quanlybao);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return BaoList;
    }

    public ArrayList<QuanLyBao> BaoList_Find() {
        ArrayList<QuanLyBao> BaoList = new ArrayList<QuanLyBao>();
        con = DAO.getConnection();
        String show = "select TaiLieu.MaTaiLieu, MaBao, TenBao, NgayPhatHanh, TenNXB,TenTaiLieu, SoBan from Bao inner join TaiLieu on Bao.MaTaiLieu = TaiLieu.MaTaiLieu Where TenBao LIKE N'" + txtTenBao1.getText() + "%'";
        try {
            st = con.createStatement();
            rs = st.executeQuery(show);
            QuanLyBao quanlybao;
            while (rs.next()) {
                quanlybao = new QuanLyBao(rs.getString("MaTaiLieu"), rs.getString("MaBao"), rs.getString("TenBao"), rs.getString("NgayPhatHanh"), rs.getString("TenNXB"), rs.getInt("SoBan"), rs.getString("TenTaiLieu"));
                BaoList.add(quanlybao);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return BaoList;
    }

    public void Show() {
        ArrayList<QuanLyBao> list = BaoList();
        DefaultTableModel model = (DefaultTableModel) tbBao.getModel();
        Object[] row = new Object[7];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getMaTaiLieu();
            row[1] = list.get(i).getMaBao();
            row[2] = list.get(i).getTenBao();
            row[3] = list.get(i).getNgayPhatHanh();
            row[4] = list.get(i).getTenNXB();
            row[5] = list.get(i).getTenTaiLieu();
            row[6] = list.get(i).getSoBan();
            model.addRow(row);
        }
    }


    private void txtMaBaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaBaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaBaoActionPerformed

    private void txtTenBaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenBaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenBaoActionPerformed

    private void txtMaTaiLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaTaiLieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaTaiLieuActionPerformed

    private void txtTenTaiLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenTaiLieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenTaiLieuActionPerformed

    private void txtSoBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoBanActionPerformed

    private void txtNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNXBActionPerformed

    private void txtTenBao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenBao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenBao1ActionPerformed

    private void tbBaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBaoMouseClicked
        try {
            int i = tbBao.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tbBao.getModel();
            Date dateFormat = new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(i, 3));
            txtNgayPH.setDate(dateFormat);
            txtMaTaiLieu.setText(model.getValueAt(i, 0).toString());
            txtMaBao.setText(model.getValueAt(i, 1).toString());
            txtTenBao.setText(model.getValueAt(i, 2).toString());
            txtNXB.setText(model.getValueAt(i, 4).toString());
            txtTenTaiLieu.setText(model.getValueAt(i, 5).toString());
            txtSoBan.setText(model.getValueAt(i, 6).toString());

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_tbBaoMouseClicked

    private void txtTenBao1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenBao1KeyPressed
        try {
            ArrayList<QuanLyBao> findbao = BaoList_Find();
            DefaultTableModel model = (DefaultTableModel) tbBao.getModel();
            model.setRowCount(0);
            Object[] row = new Object[7];
            for (int i = 0; i < findbao.size(); i++) {
                row[0] = findbao.get(i).getMaTaiLieu();
                row[1] = findbao.get(i).getMaBao();
                row[2] = findbao.get(i).getTenBao();
                row[3] = findbao.get(i).getNgayPhatHanh();
                row[4] = findbao.get(i).getTenNXB();
                row[5] = findbao.get(i).getTenTaiLieu();
                row[6] = findbao.get(i).getSoBan();
                model.addRow(row);
            }

            con.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_txtTenBao1KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        A.setText("");
        B.setText("");
        E.setText("");
        F.setText("");
        txtMaBao.setText("");
        txtTenBao.setText("");
        txtNXB.setText("");
        txtTenBao1.setText("");
        txtSoBan.setText("");
        Date date = new Date();
        txtNgayPH.setDate(date);
        DefaultTableModel model = (DefaultTableModel) tbBao.getModel();
        model.setRowCount(0);
        Show();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnReload1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReload1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnReload1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BAO_FORM1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BAO_FORM1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BAO_FORM1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BAO_FORM1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BAO_FORM1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel B;
    private javax.swing.JLabel E;
    private javax.swing.JLabel F;
    private javax.swing.JButton btnReload1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbBao;
    private javax.swing.JTextField txtMaBao;
    private javax.swing.JTextField txtMaTaiLieu;
    private javax.swing.JTextField txtNXB;
    private com.toedter.calendar.JDateChooser txtNgayPH;
    private javax.swing.JTextField txtSoBan;
    private javax.swing.JTextField txtTenBao;
    private javax.swing.JTextField txtTenBao1;
    private javax.swing.JTextField txtTenTaiLieu;
    // End of variables declaration//GEN-END:variables
}
